version: '3.8'

services:
  database:
    image: inf23dw2g05e/inf23dw2g05e:database
    command: --default-authentication-plugin=mysql_native_password
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    depends_on:
      database:
        condition: service_healthy
    image: inf23dw2g05e/inf23dw2g05e:api
    container_name: api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
       NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - shared_network
    

  react:
    depends_on:
      api:
        condition: service_healthy
    image: inf23dw2g05e/inf23dw2g05e:react
    container_name: react
    ports:
      - 3006:3006
    networks:
      - shared_network
    

networks:
  shared_network:
    driver: bridge